### ISSUE TITLE
Automate CloudFront provisioning

### ISSUE THREAD

**Issue by KlaasH** [azavea/tilegarden#29]
Use [Terraform](https://www.terraform.io/) to add the `Accept: image/png` proxy needed to make images work.

**Comment by mattdelsordo** [comment]
Use following configuration settings:
 * Origin Domain Name: `API Gateway URL`
 * Origin Path: `/latest`
 * `HTTPS only`
 * Origin Custom Headers: `Accept`|`image/png`
 * Viewer Protocol Policy: `Redirect HTTP to HTTPS`
 * Allowed HTTP Methods: `GET, HEAD, OPTIONS`
 * Object Caching: `Customize`
    * Default TTL: `1`
