### ISSUE TITLE
Identify/fix tile shearing issue

### ISSUE THREAD

**Issue by mattdelsordo** [azavea/tilegarden#43]
Matt suggested it may be a mapnik buffer size issue.

**Comment by KlaasH** [comment]
This didn't used to happen but now seems to happen pretty reliably, so this might be a situation where `git bisect` could be handy for zeroing in on the problem.

**Comment by mattdelsordo** [comment]
Going back through the commits (to develop, at least) where serving tiles works, there never seems to have been a point that this wasn't happening. I think it was either just really hard to notice early on due to the scarcity of the `pa_gardens` data.
