### ISSUE TITLE
Spin up Lambnik

### ISSUE THREAD

**Issue by KlaasH** [azavea/tilegarden#5]
Clone the [Lambnik](https://github.com/azavea/lambnik/) repo and get it running, at least to the extent of seeing the working map when you open the demo HTML file while the containers are running (switch to the commented-out tile URL [here](https://github.com/azavea/lambnik/blob/develop/src/demo/index.html#L31)).

This is just to have a point of reference and won't produce anything concrete (unless you run into issues that are worth fixing over on that repo).

**Comment by mattdelsordo** [comment]
![screenshot_20180608_094511](https://user-images.githubusercontent.com/16990679/41161810-05dda796-6b02-11e8-880a-a38acd894f6a.png)
Managed to get Lambnik running locally.

Steps:
 * In index.html, un-comment-out local URL.
 * Run './scripts/update.sh'
 * Run './scripts/server.sh'
