### ISSUE TITLE
Set up all-local development environment

### ISSUE THREAD

**Issue by KlaasH** [azavea/tilegarden#8]
If it doesn't end up getting created in the course of doing #7, add config/tooling to make a fully-local development environment.

Some priorities include:
- Ease of use setup/activation
- Fast, preferably automatic reloading
- High overlap and minimal duplication of code and config between local/development and remote/deployed

**Comment by mattdelsordo** [comment]
Note for the future: pre-existing setup requires resetting the database password after every deployment since Chalice doesn't support ENV templating in the config, see if this can be done in whichever deployment framework is settled on.
